from turtle import*
screen=Screen()
screen.register_shape('truelove.gif')
shape('truelove.gif')
t = Turtle()
wn = Screen()
wn.title("true love")
begin_fill()
color("red")
left(45)
forward(200)
circle(73,221.37)
left(180)
circle(73,221.37)
forward(200)
end_fill()
